export const BILL_LIST_REQUEST = 'BILL_LIST_REQUEST';
export const BILL_LIST_SUCCESS = 'BILL_LIST_SUCCESS';
export const BILL_LIST_FAIL = 'BILL_LIST_FAIL';

export const BILL_UPDATE_REQUEST = 'BILL_UPDATE_REQUEST';
export const BILL_UPDATE_SUCCESS = 'BILL_UPDATE_SUCCESS';
export const BILL_UPDATE_FAIL = 'BILL_UPDATE_FAIL';

export const BILL_UPDATE_STATUS_REQUEST = 'BILL_UPDATE_STATUS_REQUEST';
export const BILL_UPDATE_STATUS_SUCCESS = 'BILL_UPDATE_STATUS_SUCCESS';
export const BILL_UPDATE_STATUS_FAIL = 'BILL_UPDATE_STATUS_FAIL';

export const BILL_DELETE_REQUEST = 'BILL_DELETE_REQUEST';
export const BILL_DELETE_SUCCESS = 'BILL_DELETE_SUCCESS';
export const BILL_DELETE_FAIL = 'BILL_DELETE_FAIL';
