export const CREATE_REQUEST_ROOM_REQUEST = 'CREATE_REQUEST_ROOM_REQUEST';
export const CREATE_REQUEST_ROOM_SUCCESS = 'CREATE_REQUEST_ROOM_SUCCESS';
export const CREATE_REQUEST_ROOM_FAIL = 'CREATE_REQUEST_ROOM_FAIL';

export const REQUEST_ROOM_LIST_REQUEST = 'REQUEST_ROOM_LIST_REQUEST';
export const REQUEST_ROOM_LIST_SUCCESS = 'REQUEST_ROOM_LIST_SUCCESS';
export const REQUEST_ROOM_LIST_FAIL = 'REQUEST_ROOM_LIST_FAIL';

export const REQUEST_ROOM_DELETE_REQUEST = 'REQUEST_ROOM_DELETE_REQUEST';
export const REQUEST_ROOM_DELETE_SUCCESS = 'REQUEST_ROOM_DELETE_SUCCESS';
export const REQUEST_ROOM_DELETE_FAIL = 'REQUEST_ROOM_DELETE_FAIL';

export const REQUEST_ROOM_UPDATE_STATUS_REQUEST = 'REQUEST_ROOM_UPDATE_STATUS_REQUEST';
export const REQUEST_ROOM_UPDATE_STATUS_SUCCESS = 'REQUEST_ROOM_UPDATE_STATUS_SUCCESS';
export const REQUEST_ROOM_UPDATE_STATUS_FAIL = 'REQUEST_ROOM_UPDATE_STATUS_FAIL';
