export const ROOM_FROM_BUIID_LIST_REQUEST = 'ROOM_FROM_BUIID_LIST_REQUEST';
export const ROOM_FROM_BUIID_LIST_SUCCESS = 'ROOM_FROM_BUIID_LIST_SUCCESS';
export const ROOM_FROM_BUIID_LIST_FAIL = 'ROOM_FROM_BUIID_LIST_FAIL';

export const ROOM_LIST_REQUEST = 'ROOM_LIST_REQUEST';
export const ROOM_LIST_SUCCESS = 'ROOM_LIST_SUCCESS';
export const ROOM_LIST_FAIL = 'ROOM_LIST_FAIL';

export const ROOM_CREATE_REQUEST = 'ROOM_CREATE_REQUEST';
export const ROOM_CREATE_SUCCESS = 'ROOM_CREATE_SUCCESS';
export const ROOM_CREATE_FAIL = 'ROOM_CREATE_FAIL';

export const ROOM_UPDATE_REQUEST = 'ROOM_UPDATE_REQUEST';
export const ROOM_UPDATE_SUCCESS = 'ROOM_UPDATE_SUCCESS';
export const ROOM_UPDATE_FAIL = 'ROOM_UPDATE_FAIL';

export const ROOM_DELETE_REQUEST = 'ROOM_DELETE_REQUEST';
export const ROOM_DELETE_SUCCESS = 'ROOM_DELETE_SUCCESS';
export const ROOM_DELETE_FAIL = 'ROOM_DELETE_FAIL';

export const ROOM_DETAIL_BY_ID_REQUEST = 'ROOM_DETAIL_BY_ID_REQUEST';
export const ROOM_DETAIL_BY_ID_SUCCESS = 'ROOM_DETAIL_BY_ID_SUCCESS';
export const ROOM_DETAIL_BY_ID_FAIL = 'ROOM_DETAIL_BY_ID_FAIL';
