export const BUILDING_LIST_REQUEST = 'BUILDING_LIST_REQUEST';
export const BUILDING_LIST_SUCCESS = 'BUILDING_LIST_SUCCESS';
export const BUILDING_LIST_FAIL = 'BUILDING_LIST_FAIL';

export const BUILDING_DETAIL_REQUEST = 'BUILDING_DETAIL_REQUEST';
export const BUILDING_DETAIL_SUCCESS = 'BUILDING_DETAIL_SUCCESS';
export const BUILDING_DETAIL_FAIL = 'BUILDING_DETAIL_FAIL';

export const BUILDING_CREATE_REQUEST = 'BUILDING_CREATE_REQUEST';
export const BUILDING_CREATE_SUCCESS = 'BUILDING_CREATE_SUCCESS';
export const BUILDING_CREATE_FAIL = 'BUILDING_CREATE_FAIL';

export const BUILDING_REMOVE_REQUEST = 'BUILDING_REMOVE_REQUEST';
export const BUILDING_REMOVE_SUCCESS = 'BUILDING_REMOVE_SUCCESS';
export const BUILDING_REMOVE_FAIL = 'BUILDING_REMOVE_FAIL';
