export const BUILDING_LIST_REQUEST = 'BUILDING_LIST_REQUEST';
export const BUILDING_LIST_SUCCESS = 'BUILDING_LIST_SUCCESS';
export const BUILDING_LIST_FAIL = 'BUILDING_LIST_FAIL';

export const BUILDING_DETAIL_REQUEST = 'BUILDING_DETAIL_REQUEST';
export const BUILDING_DETAIL_SUCCESS = 'BUILDING_DETAIL_SUCCESS';
export const BUILDING_DETAIL_FAIL = 'BUILDING_DETAIL_FAIL';

export const BUILDING_CREATE_REQUEST = 'BUILDING_CREATE_REQUEST';
export const BUILDING_CREATE_SUCCESS = 'BUILDING_CREATE_SUCCESS';
export const BUILDING_CREATE_FAIL = 'BUILDING_CREATE_FAIL';

export const BUILDING_UPDATE_REQUEST = 'BUILDING_UPDATE_REQUEST';
export const BUILDING_UPDATE_SUCCESS = 'BUILDING_UPDATE_SUCCESS';
export const BUILDING_UPDATE_FAIL = 'BUILDING_UPDATE_FAIL';

export const BUILDING_DELETE_REQUEST = 'BUILDING_DELETE_REQUEST';
export const BUILDING_DELETE_SUCCESS = 'BUILDING_DELETE_SUCCESS';
export const BUILDING_DELETE_FAIL = 'BUILDING_DELETE_FAIL';
