export const CREATE_REQUEST_ROOM_REQUEST = 'CREATE_REQUEST_ROOM_REQUEST';
export const CREATE_REQUEST_ROOM_SUCCESS = 'CREATE_REQUEST_ROOM_SUCCESS';
export const CREATE_REQUEST_ROOM_FAIL = 'CREATE_REQUEST_ROOM_FAIL';

export const REQUEST_ROOM_LIST_REQUEST = 'REQUEST_ROOM_LIST_REQUEST';
export const REQUEST_ROOM_LIST_SUCCESS = 'REQUEST_ROOM_LIST_SUCCESS';
export const REQUEST_ROOM_LIST_FAIL = 'REQUEST_ROOM_LIST_FAIL';
