export const ROOM_CATEGORY_LIST_REQUEST = 'ROOM_CATEGORY_LIST_REQUEST';
export const ROOM_CATEGORY_LIST_SUCCESS = 'ROOM_CATEGORY_LIST_SUCCESS';
export const ROOM_CATEGORY_LIST_FAIL = 'ROOM_CATEGORY_LIST_FAIL';

export const ROOM_CATEGORY_DETAIL_REQUEST = 'ROOM_CATEGORY_DETAIL_REQUEST';
export const ROOM_CATEGORY_DETAIL_SUCCESS = 'ROOM_CATEGORY_DETAIL_SUCCESS';
export const ROOM_CATEGORY_DETAIL_FAIL = 'ROOM_CATEGORY_DETAIL_FAIL';

export const ROOM_CATEGORY_CREATE_REQUEST = 'ROOM_CATEGORY_CREATE_REQUEST';
export const ROOM_CATEGORY_CREATE_SUCCESS = 'ROOM_CATEGORY_CREATE_SUCCESS';
export const ROOM_CATEGORY_CREATE_FAIL = 'ROOM_CATEGORY_CREATE_FAIL';

export const ROOM_CATEGORY_UPDATE_REQUEST = 'ROOM_CATEGORY_UPDATE_REQUEST';
export const ROOM_CATEGORY_UPDATE_SUCCESS = 'ROOM_CATEGORY_UPDATE_SUCCESS';
export const ROOM_CATEGORY_UPDATE_FAIL = 'ROOM_CATEGORY_UPDATE_FAIL';

export const ROOM_CATEGORY_DELETE_REQUEST = 'ROOM_CATEGORY_DELETE_REQUEST';
export const ROOM_CATEGORY_DELETE_SUCCESS = 'ROOM_CATEGORY_DELETE_SUCCESS';
export const ROOM_CATEGORY_DELETE_FAIL = 'ROOM_CATEGORY_DELETE_FAIL';
