export const ROOM_FROM_BUIID_LIST_REQUEST = 'ROOM_FROM_BUIID_LIST_REQUEST';
export const ROOM_FROM_BUIID_LIST_SUCCESS = 'ROOM_FROM_BUIID_LIST_SUCCESS';
export const ROOM_FROM_BUIID_LIST_FAIL = 'ROOM_FROM_BUIID_LIST_FAIL';
