export const STUDENT_LOGIN_REQUEST = 'STUDENT_LOGIN_REQUEST';
export const STUDENT_LOGIN_SUCCESS = 'STUDENT_LOGIN_SUCESS';
export const STUDENT_LOGIN_FAIL = 'STUDENT_LOGIN_FAIL';
export const STUDENT_LOGOUT = 'STUDENT_LOGOUT';

export const STUDENT_REGISTER_REQUEST = 'STUDENT_REGISTER_REQUEST';
export const STUDENT_REGISTER_SUCESS = 'STUDENT_REGISTER_SUCESS';
export const STUDENT_REGISTER_FAIL = 'STUDENT_REGISTER_FAIL';

export const STUDENT_GET_PROFILE_REQUEST = 'STUDENT_GET_PROFILE_REQUEST';
export const STUDENT_GET_PROFILE_SUCCESS = 'STUDENT_GET_PROFILE_SUCCESS';
export const STUDENT_GET_PROFILE_FAIL = 'STUDENT_GET_PROFILE_FAIL';
export const STUDENT_GET_PROFILE_RESET = 'STUDENT_GET_PROFILE_RESET';

export const STUDENT_UPDATE_PROFILE_REQUEST = 'STUDENT_UPDATE_PROFILE_REQUEST';
export const STUDENT_UPDATE_PROFILE_SUCCESS = 'STUDENT_UPDATE_PROFILE_SUCCESS';
export const STUDENT_UPDATE_PROFILE_FAIL = 'STUDENT_UPDATE_PROFILE_FAIL';
export const STUDENT_UPDATE_PROFILE_RESET = 'STUDENT_UPDATE_PROFILE_RESET';

export const STUDENT_CHANGE_PASSWORD_REQUEST = 'STUDENT_CHANGE_PASSWORD_REQUEST';
export const STUDENT_CHANGE_PASSWORD_SUCCESS = 'STUDENT_CHANGE_PASSWORD_SUCCESS';
export const STUDENT_CHANGE_PASSWORD_FAIL = 'STUDENT_CHANGE_PASSWORD_FAIL';
